name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://1761-83-229-24-163.ngrok-free.app/library/login
            https://1761-83-229-24-163.ngrok-free.app/
            https://1761-83-229-24-163.ngrok-free.app/library/browse
            https://1761-83-229-24-163.ngrok-free.app/library/review
            https://1761-83-229-24-163.ngrok-free.app/library/archive
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage